# 将 Hugo 博客构建后部署到 Github Pages
name: Test chaat build

# 在 master 主干分支的任何 push 事件都会触发本 DevOps 工作流水线
on:  [push, pull_request]

# 以下是本串行执行工作流的所有组成部分
jobs:
  # 这里只定义了一个名为 "deploy" 的多步骤作业
  build-all-md:
    # 将后续的所有工作步骤都运行在最新版的 ubuntu 操作系统上
    runs-on: ubuntu-latest

    # 本构建和部署作业的所有步骤定义如下
    steps:

    # Step 1 - Checks-out Hugo 博客代码库到 $GITHUB_WORKSPACE
    - name: Checkout blog code repo
      uses: actions/checkout@v2 # 这是 Github 官方提供的一个动作模块
      with:
          submodules: true  # 同步更新所使用的 Hugo 模板
          fetch-depth: 0    # 更新到该模板最新的版本

    # Runs a set of commands using the runners shell
    - name: Setup claat and build codelabs
      run: |
        curl -L https://github.com/googlecodelabs/tools/releases/download/v2.2.4/claat-linux-amd64 > claat
        chmod +x claat
        ./claat *.md